### ISSUE TITLE
Missing raw data files on Zenodo

### ISSUE THREAD

**Issue by mavel101** [mrirecon/nlinv-net#2]
There seems to be raw data missing on Zenodo, as the download script "00_data/01_download_raw_data/01_download_rt_data.sh" fails. At least the file "https://zenodo.org/record/10492337/files/vol0023_vis1.hdr $RAWDIR/vol0023_vis1.hdr" is missing. The datasets should be checked for completeness.

**Comment by mblum94** [comment]
The dataset is now complete.
