### ISSUE TITLE
Retraining network doesnt work

### ISSUE THREAD

**Issue by mavel101** [mrirecon/nlinv-net#3]
I tried to run the script "/01_scripts/21_train_network_rt.sh 11_networks_rt/<network>/" with the "11_resnet_mse" network, but the script isnt running as a "ksp" cfl file is missing. Probably these files can be created with the script "01_create_rt_svd.sh", but as the raw data download failed for me (see other issue), I couldnt test it.
If "01_create_rt_svd.sh" does create the required files, this could be added to the README.

**Comment by mblum94** [comment]
Thanks for pointing this out. The README is updated.
